name: greeting
run-name: ${{ github.actor }} This is action for model classifier
on: 
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
