name: Code default

on:
    pull_request:
      types:
        - opened
      branches:
        - 'main/**'

jobs:
    initial:
        runs-on: ubuntu-latest
        steps:
        - name: Placeholder
          run: |
            echo "Will add code checks here in next challenge"