name: Code default

on:
    pull_request:
      types: [opened, reopened]
      branches:
        - 'main'

jobs:
    test-action:
        runs-on: ubuntu-latest
        steps:
        - name: Placeholder
          run: |
            echo "The pull request action triggered successful"