name: Code default

on:
    pull_request:
      types: [opened, reopened]
      branches:
        - 'main'

jobs:
    job1:
        name: linting
        runs-on: ubuntu-latest
        steps:
        - name: Placeholder
          run: |
            echo "The pull request action triggered successful"
    job2:
      name: linting
      runs-on: ubuntu-latest
      steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Use Python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Flake8
        run: |
          python -m pip install flake8
      - name: Run linting tests
        run: | 
          flake8 src/model/
    job3:
      name: unit-test
      runs-on: ubuntu-latest
      steps: 
      - name: Check out repo
        uses: actions/checkout@main
      - name: Use Python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Pytest
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: | 
          pytest tests/
    