name: Training on datasets

on:
    push:
        branches:
            - 'main'
jobs:
    job1:
        name: experiment
        runs-on: ubuntu-latest
        environment: development
        steps:
        - name: Check out repo
          uses: actions/checkout@main
        - name: Install az ml extension
          run: az extension add -n ml -y
        - name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
        - name: Training
          run: az ml job create --file src/job.yml --resource-group mlops-demo --workspace-name mlops-demo --stream
    job2:
        name: production
        runs-on: ubuntu-latest
        environment: production
        needs: job1
        steps:
        - name: Check out repo
          uses: actions/checkout@main
        - name: Install az ml extension
          run: az extension add -n ml -y
        - name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
        - name: Training
          run: az ml job create --file src/job_prod.yml --resource-group mlops-demo --workspace-name mlops-demo  --stream