name: Deployment model

on:
   workflow_dispatch:

jobs:
    job1:
        name: Create Endpoint
        runs-on: ubuntu-latest
        environment: production
        steps:
        - name: Check out repo
          uses: actions/checkout@main
        - name: Install az ml extension
          run: az extension add -n ml -y
        - name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
        - name: Create endpoint
          run: az ml online-endpoint create --file src/create_endpoint.yml --resource-group mlops_practice --workspace-name mlops_practice
    job2:
        name: Deploy Model
        runs-on: ubuntu-latest
        environment: production
        needs: job1
        steps:
        - name: Check out repo
          uses: actions/checkout@main
        - name: Install az ml extension
          run: az extension add -n ml -y
        - name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
        - name: Deploy Model
          run: az ml online-deployment create --file src/deploy_model.yml --resource-group mlops_demo --workspace-name mlops_demo --all-traffic
